name: Compile LaTeX to PDF

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile LaTeX to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: report/master.tex
        work_in_root_file_dir: true

    - name: Move PDF to desired location
      run: mv master.pdf report/master.pdf

    - name: Upload PDF
      uses: actions/upload-artifact@v1
      with:
        name: master.pdf
        path: report/master.pdf

    - name: Save logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: logs
        path: .

